generatorConfig:
  port: 1234
  final: FINAL

proxy: #clash subscriptions
  - https://xxxxx
  - https://yyyyy

rule: #rule providers
  - name: CHINA
    url: 
      - https://raw.githubusercontent.com/Biobots/personalClashRule/master/China.yaml
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
  - name: PROXY
    url: 
      - https://raw.githubusercontent.com/Biobots/personalClashRule/master/Workspace.yaml
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
  - name: STEAM
    url: 
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Game/Steam.yaml
  - name: BLOCK
    url: 
      - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml

groups: #proxy groups
  - name: PROXY
    keywords: 
    type: select
    subgroup: [hk, us, jp, DIRECT, REJECT]

  - name: STEAM
    keywords: 
    type: select
    subgroup: [hk, us, jp, DIRECT, REJECT]

  - name: BLOCK
    keywords: 
    type: select
    subgroup: [REJECT, DIRECT]

  - name: CHINA
    keywords: 
    type: select
    subgroup: [DIRECT, REJECT]

  - name: FINAL
    keywords: 
    type: select
    subgroup: [PROXY, DIRECT, REJECT]

  - name: hk
    keywords: 香港
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    subgroup: []

  - name: us
    keywords: 美国
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    subgroup: []

  - name: jp
    keywords: 日本
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    subgroup: []