generatorConfig:
  - port: 1234

proxy: #clash subscriptions
  - https://xxxxx
  - https://yyyyy

rule: #rule providers
  - name: test1
    url: 
      - https://github.com/Biobots/personalClashRule/raw/master/Workspace.yaml
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
  - name: test2
    url: 
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml

groups: #proxy groups
  - name: test1
    keywords: 香港 上海
    type: select
    direct: true
    reject: true

  - name: test2
    keywords: 香港 高级
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    direct: false
    reject: true