generatorConfig:
  port: 1234

proxy: #clash subscriptions
  - https://xxxxx
  - https://yyyyy

rule: #rule providers
  - name: group1
    url: 
      - https://github.com/Biobots/personalClashRule/raw/master/Workspace.yaml
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
  - name: group2
    url: 
      - https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml

groups: #proxy groups
  - name: group1
    keywords: 
    type: select
    subgroup: [DIRECT, REJECT, filter1]

  - name: group2
    keywords: 
    type: select
    subgroup: [DIRECT, REJECT, filter2]

  - name: filter1
    keywords: 香港
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    subgroup: []

  - name: filter2
    keywords: 美国
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    subgroup: []