proxy:
  - https://xxxxx
  - https://yyyyy

src:
  - '香港'
  - '美国'
  - '日本'
  - '台湾'
  - '澳洲'

dst:
  - '上海'
  - '北京'
  - '广州'

rule:
  - 
    name: test1
    url: https://github.com/Biobots/personalClashRule/raw/master/Workspace.yaml
  - 
    name: test2
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml

groups:
  -
    name: test1
    group: 上海
    type: select

  -
    name: test2
    group: 广州
    type: select