proxy: #clash subscriptions
  - https://xxxxx
  - https://yyyyy

src: #useless
  - '香港'
  - '美国'
  - '日本'
  - '台湾'
  - '澳洲'

dst: #useless
  - '上海'
  - '北京'
  - '广州'

rule: #rule providers
  - 
    name: test1
    url: https://github.com/Biobots/personalClashRule/raw/master/Workspace.yaml
  - 
    name: test2
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml

groups: #proxy groups
  - name: test1
    keywords: 香港 上海
    type: select
    direct: true
    reject: true

  - name: test2
    keywords: 香港 高级
    type: urltest
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    direct: false
    reject: true